# Permalinks
permalink: pretty
relative_permalinks: true

# Site settings
title: Davis Martin
email: davisshippmartin@gmail.com
description: My Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davissmartin.com" # the base hostname & protocol for your site
twitter_username: "davis_martin_"
github_username: "davismartin"
facebook_username: "davis.martin"

# Build settings
markdown: kramdown
