# Permalinks
permalink: pretty

# Site settings
title: Davis Martin
email: davisshippmartin@gmail.com
description: My Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davissmartin.com" # the base hostname & protocol for your site
twitter_username: "davis_martin_"
github_username: "davismartin"
facebook_username: "davis.martin"
linkedin_username: "davismartindev"
googleplus_username: "113904257175185224261"
resume: "https://drive.google.com/file/d/0B9eaEYGl2BxwZ0Z6OVYwZURhZXM/view?usp=sharing"

# Build settings
markdown: kramdown
exclude: [node_modules]