# Permalinks
permalink: pretty
relative_permalinks: true

# Site settings
title: Davis Martin
email: davisshippmartin@gmail.com
description: My Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davismartin.com" # the base hostname & protocol for your site
twitter_username:
github_username:  

# Build settings
markdown: kramdown
